app:
  env_name: "local" # local | staging | prod
  port: "8080"      #порт на котором будет запущен сервер
  readTimeout: 12   #(секунды) Если клиент не отправит полный запрос за указанное время, соединение будет закрыто
  writeTimeout: 12  #(секунды) Если сервер не успеет отправить ответ клиенту за указанное время, соединение закроется.

#Если изменить параметры подключения к БД, нужно будет изменить их для самой БД в docker-compose.yml
db:
  host: "db"
  port: "5432"
  user: "postgres"
  password: "somepassword"
  name: "postgres"
  ssl: "verify-full"                # disable | require | verify-ca | verify-full
  sslrootcert: "/path/to/root.crt"  # Корневой сертификат
  sslcert: "/path/to/client.crt"    # Клиентский сертификат
  sslkey: "/path/to/client.key"     # Приватный ключ
